CREATE TABLE aluno
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(255),
    telefone VARCHAR(255),
    tipo     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_aluno PRIMARY KEY (id)
);

CREATE TABLE aluno_disponibilidade
(
    aluno_id        BIGINT NOT NULL,
    disponibilidade VARCHAR(255)
);

CREATE TABLE aluno_materia
(
    aluno_id   BIGINT NOT NULL,
    materia_id BIGINT NOT NULL,
    CONSTRAINT pk_aluno_materia PRIMARY KEY (aluno_id, materia_id)
);

CREATE TABLE encontro
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    monitor_id     BIGINT                                  NOT NULL,
    beneficiado_id BIGINT                                  NOT NULL,
    materia_id     BIGINT                                  NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    data_hora      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    observacoes    VARCHAR(255),
    CONSTRAINT pk_encontro PRIMARY KEY (id)
);

CREATE TABLE materia
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_materia PRIMARY KEY (id)
);