CREATE TABLE encontro
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    monitor_id  BIGINT                                  NOT NULL,
    beneficiado VARCHAR(255)                            NOT NULL,
    telefone    VARCHAR(255),
    materia     VARCHAR(255)                            NOT NULL,
    assunto     VARCHAR(255),
    status      VARCHAR(255)                            NOT NULL,
    data_hora   TIMESTAMP WITHOUT TIME ZONE,
    observacoes VARCHAR(1000),
    CONSTRAINT pk_encontro PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome    VARCHAR(255)                            NOT NULL,
    senha   VARCHAR(255)                            NOT NULL,
    tipo    VARCHAR(255)                            NOT NULL,
    materia VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

ALTER TABLE encontro
    ADD CONSTRAINT FK_ENCONTRO_ON_MONITOR FOREIGN KEY (monitor_id) REFERENCES usuario (id);